## NumPy Arrays

np.array(1 list as args)

In [3]:
import numpy as np

In [29]:
arr_1d = np.array([1,2,3]);    # only 1 list(array) as argument
arr_2d = np.array([ [1,2,3], [4,5,6] ]);

print("1D ARRAY: ", arr_1d);
print("2D ARRAY: ", arr_2d);


1D ARRAY:  [1 2 3]
2D ARRAY:  [[1 2 3]
 [4 5 6]]


in list, elements repeated when list is multiplied by scalar;
but in np_array- elements value are in-place doubled, tripled, etc

##### creation
 arange(start, stop, step)- stop is most needed

 zeros((row, col)) - zeros full matrix
 
 ones ((row, col)) - ones full matrix
 
 full ((row, col)) - cosntant val full matrix
 
 random((row, col))   - random matrix

In [30]:
py_list = [1,2,3]
np_array = np.array([1,2,3])

print("List: ", py_list*2)         
print("List: ", np_array*2)

List:  [1, 2, 3, 1, 2, 3]
List:  [2 4 6]


In [31]:
zeros = np.zeros((2,3))
ones  = np.ones((4,2))
random = np.random.random((2,3)) 
seq = np.arange(1,17,2)

print(zeros, "\n", ones, "\n", random , "\n", seq)

[[0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[0.44440591 0.96346975 0.55684319]
 [0.8375449  0.72140053 0.85486869]] 
 [ 1  3  5  7  9 11 13 15]


In [32]:
import time
start = time.time()
py_list = [i*2 for i in range (10000000)]
print("List operation took time: ", time.time() - start)

start = time.time()
np_array = np.arange(10000000) * 2  #arange used to create array till this stop
print("Numpy array operation took time: ", time.time() - start)

List operation took time:  0.5268025398254395
Numpy array operation took time:  0.04126381874084473


### Properties

###### shape- tells (row, col)
###### size - total elements
###### ndim - dimension of array
###### dtype - data type of elements, based on priorit if heterogenous elements
###### T - gives the transpose


###### reshape((newrow, newcol)) - reshape r * c
###### flatten - makes the array as 1 * 1, but displays copy
###### ravel - same as flatten, but displays original view