#### Indexing and Slicing
arr[start:stop:step]   ||   arr[-i] for negative index

printing specific rows and columns - arr[row_start : row_e, col_s : col_end]

In [31]:
import numpy as np

In [32]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing: ", arr[2:6])
print("With step: ", arr[2:7:2])
print("Negative index: ", arr[-4])

Basic slicing:  [3 4 5 6]
With step:  [3 5 7]
Negative index:  6


In [33]:
arr2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print("Spec. element: ", arr2d[2,2])
print("entire row: ", arr2d[2])
print("entire col: ", arr2d[:,1])

Spec. element:  9
entire row:  [7 8 9]
entire col:  [2 5 8]


### Sorting and Filtering

vector sort : np.sort(array_name) 

matrix sort (by col): np.sort(matrix_name, axis = 0), // axis = 1 for sort by row

axis is used to do operations and tell which way-row or column

filter : arr_name[expression/mask]....mask is storing expression and then using mask wherever needed
##### Fancy indexing vs np.where()
np.where(expression/mask, if true then?, if not then?)...to get indices..||... either give all three or only condition




In [34]:
mat = np.array([[2,55,3],[21,72,34],[23,1,2]])
print("Sorted matrix by column: ", np.sort(mat, axis = 0))

array = np.array([2,3,54,67,23,4,43,542,34,232,354,56,1,2,3,4,5,6,24,56])
even = array[array % 2 == 0]
print("Even numbers in array: ", even)

where_res1 = np.where(array > 6)                    # only condition given - gives indices
where_res2 = np.where(array > 6, " > 6", "<= 6" )   # all parameters given - gives final array
print("where result indices: ", where_res1)
print("values of where_res: ", array[where_res1])  
print("values of where_res: ", where_res2)  



Sorted matrix by column:  [[ 2  1  2]
 [21 55  3]
 [23 72 34]]
Even numbers in array:  [  2  54   4 542  34 232 354  56   2   4   6  24  56]
where result indices:  (array([ 2,  3,  4,  6,  7,  8,  9, 10, 11, 18, 19]),)
values of where_res:  [ 54  67  23  43 542  34 232 354  56  24  56]
values of where_res:  ['<= 6' '<= 6' ' > 6' ' > 6' ' > 6' '<= 6' ' > 6' ' > 6' ' > 6' ' > 6'
 ' > 6' ' > 6' '<= 6' '<= 6' '<= 6' '<= 6' '<= 6' '<= 6' ' > 6' ' > 6']


## Adding and Removing Data
np.concatenate((array1, arr2)) - add arr2 at end of array1
np.vstack((array, new_row)) - to add a new row at last
np.hstack((array, new_col)) - to add a new col at last

np.delete(arr, indices) - delete certain index
np.delete(arr, start, stop, step) - multiple deletions

arr.shape - a property to check compaitibility of arrays 

In [35]:
vector1 = np.array([1,2,3])
vector2 = np.array([4, 5, 6])
matrix1 = np.array([[1,2],[3,4]])
new1 = np.array([5,6]); new2 = np.array([[7],[8]])

print("concatenation: ", np.concatenate((vector1, vector2)))
print("new row added: ", np.vstack((matrix1, new1)))
print("new col added: ", np.hstack((matrix1, new2)))


concatenation:  [1 2 3 4 5 6]
new row added:  [[1 2]
 [3 4]
 [5 6]]
new col added:  [[1 2 7]
 [3 4 8]]
