In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#DATA - sales of 6 months of 5 different companies sellin product in a online store
sales = np.array([
    [1, 218000, 230000, 230000, 232000, 234000],
    [2, 538000, 230000, 230000, 232000, 234000],
    [3, 318000, 260000, 230000, 232000, 234000],
    [4, 248000, 244000, 230000, 232000, 234000],
    [5, 258000, 320000, 230000, 232000, 234000],
    ])

# printing specific rows and columns - sales[row_start : row_e, col_s : col_end
print("Only values: \n", sales[:, 1:])

Only values: 
 [[218000 230000 230000 232000 234000]
 [218000 230000 230000 232000 234000]
 [218000 230000 230000 232000 234000]
 [218000 230000 230000 232000 234000]
 [218000 230000 230000 232000 234000]]


In [17]:
#sales in a year of combined
print("All companies combined sales: \n", np.sum(sales[:,1:], axis=0))

#sales in a year of each company
print("Each companies annual sales: \n", np.sum(sales[:,1:], axis=1))

#minimum sale by company
print("Min. sale by each company in 1 months: ", np.min(sales[: ,1:], axis=0))

#maximum sale in 1 month combined
print("Max. sale in 1 month: ", np.max(sales[: ,1:], axis=1))


All companies combined sales: 
 [1090000 1150000 1150000 1160000 1170000]
Each companies annual sales: 
 [1144000 1144000 1144000 1144000 1144000]
Min. sale by each company in 1 months:  [218000 230000 230000 232000 234000]
Max. sale in 1 month:  [234000 234000 234000 234000 234000]
